name: financial-analysis-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pandas>=1.5.0
  - numpy>=1.23.0
  - requests>=2.28.0
  - pip
  - pip:
      - pydantic>=2.0.0
      - pydantic-ai>=0.1.0
      - mlflow>=2.7.0
      - tavily-python>=0.1.4
      - python-dotenv>=1.0.0
      - ta-lib>=0.4.26

      
conda env create -f conda.yaml
conda activate financial-analysis-env
